from flymodel.client.models import query_namespaces

Namespace = query_namespaces.Namespace
PaginatedNamespace = query_namespaces.PaginatedNamespace
QueryNamespaces = query_namespaces.QueryNamespaces
QueryNamespacesVariables = query_namespaces.QueryNamespacesVariables
